=== Vaishal-Raj/eks-platform-infra/config/schema/profile.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Profile sections (also used on the resolved config)",
  "type": "object",
  "additionalProperties": false,
  "required": ["network", "endpoints","edge","alb"],
  "properties": {
    "network": {
      "type": "object",
      "additionalProperties": false,
      "required": ["az_count"],
      "properties": {
        "az_count": { "type": "integer", "minimum": 2, "maximum": 3 }
      }
    },
    "endpoints": {
      "type": "object",
      "additionalProperties": false,
      "required": ["enabled", "interface_services", "enable_s3_gateway"],
      "properties": {
        "enabled": { "type": "boolean" },
        "interface_services": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": { "type": "string", "pattern": "^[a-z0-9.-]+$" }
        },
        "enable_s3_gateway": { "type": "boolean" }
      }
    },
    "edge": {
        "type":"object",
        "additionalProperties": false,
        "required": ["enabled"],
        "properties": {
            "enabled":{"type":"boolean"}
        }
    },
     "alb": {
      "type": "object",
      "additionalProperties": false,
      "required": ["target_port", "deletion_protection"],
      "properties": {
        "target_port":         { "type": "integer", "minimum": 1, "maximum": 65535 },
        "deletion_protection": { "type": "boolean" }
      }
    }
  }
}

=== Vaishal-Raj/eks-platform-infra/config/profiles/standard.json
{
  "network": {
    "az_count": 3
  },
  "endpoints": {
    "enabled": true,
    "interface_services": [
      "ecr.api",
      "ecr.dkr",
      "sts",
      "logs",
      "secretsmanager",
      "ec2",
      "elasticloadbalancing"
    ],
    "enable_s3_gateway": true
  },
  "edge":{
    "enabled":true
  },
  "alb":{
    "target_port":8000,
    "deletion_protection":false
  }
}
